### ISSUE TITLE
Build is broken because of microflo-emscripten

### ISSUE THREAD

**Issue by bergie** [flowbased/fbp-protocol-client#55]
Should switch to the grunt-noflo-browser 1.x series to use Webpack instead of Component.io

```
warning: failed to fetch https://raw.githubusercontent.com/microflo/microflo-emscripten/master/dist/microflo-runtime.js, got 404 "Not Found"
```

Same issue as in noflo/noflo-runtime#84

**Comment by jonnor** [comment]
Can you specify `microflo-emscripten`  `0.3.28`?
